### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by sideeffffect** [rtimush/sbt-rewarn#1]
Could you please consider publishing to Maven Central? Using packages from there is always easy, even behind corporate firewalls, because Maven Central is proxied internally.

Doing so should be trivial when using [`sbt-ci-release`](https://github.com/olafurpg/sbt-ci-release)!

Thank you!

**Comment by rtimush** [comment]
I remember there were some problems with publishing sbt plugins to Maven Central, so sbt community repository at https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/ was the default. As far as I can see most other sbt plugins are not available on Maven Central either, so I'm not sure if moving just this one will be of a big help, but I will check what's needed for that.

**Comment by sideeffffect** [comment]
Maybe in the past. These days, sbt plugins are published to Maven Central and with `sbt-ci-release` it works like a charm :sunglasses:  See https://github.com/scalacenter/sbt-compatibility for example
