### ISSUE TITLE
This plugin is incompatible with sbt 1.4.0-RC2

### ISSUE THREAD

**Issue by rtimush** [rtimush/sbt-rewarn#15]
The plugin loads fine, but doesn't work. Quick investigation showed that `xsbti.compile.analysis.SourceInfo` no longer contains information about compilation warnings. 
https://github.com/sbt/sbt/issues/5892

**Comment by mushtaq** [comment]
@rtimush tried the latest snapshot `0.0.1-21-777018c`, still does not work.

**Comment by rtimush** [comment]
You can try `Global / reportAbsolutePath := false` as a workaround. The problem has been already fixed in zinc and hopefully the fix will be included in the next sbt release.

**Comment by mushtaq** [comment]
thanks! will try that.
