### ISSUE TITLE
This plugin is incompatible with sbt 1.4.0-RC1

### ISSUE THREAD

**Issue by mushtaq** [rtimush/sbt-rewarn#9]
I have been very happy using this plugin for last couple of months.

But I have to disable it today  because it prevents upgrading to sbt 1.4.0-RC1, as pointed out in https://github.com/sbt/sbt/issues/5816

**Comment by rtimush** [comment]
Can you please try `0.0.1-15-3102b36` from `resolvers += Resolver.bintrayIvyRepo("rtimush", "sbt-plugin-snapshots")`? I updated the plugin this morning to be compatible with sbt 1.4.0-RC1, but haven't put any tag yet.

**Comment by mushtaq** [comment]
Works very well, thank you!

**Comment by rtimush** [comment]
Published [0.1.1](https://github.com/rtimush/sbt-rewarn/releases/tag/v0.1.1)
